server:
  port: 8090

spring:
  application:
    name: pet_money_tool
  datasource:
    url: jdbc:mysql://host:port/pet?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
      template_update_delay: 0
      number_format: 0.##

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl